# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LieuxPropices
                                 A QGIS plugin
 Trouve les zones situées en même temps à des distances définissables du métro, des gares SNCF, des espaces verts et des piscines.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-09
        copyright            : (C) 2023 by Matthieu Ahr
        email                : matthieu.ahr@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LieuxPropices class from file LieuxPropices.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lieuxpropices import LieuxPropices
    return LieuxPropices(iface)
