# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LieuxPropices
                                 A QGIS plugin
 Trouve les zones situées en même temps à des distances définissables du métro, des gares SNCF, des espaces verts et des piscines.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Matthieu Ahr
        email                : matthieu.ahr@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsVectorLayer,
                       QgsProject,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterDistance,
                       QgsProcessingParameterVectorDestination)
from qgis import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .lieuxpropices_dialog import LieuxPropicesDialog
import os.path


class LieuxPropices:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LieuxPropices_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Lieux Propices')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LieuxPropices', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/lieuxpropices/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Trouve les zones situées en même temps à des distances définissables du métro, des gares SNCF, des espaces verts et des piscines.'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Lieux Propices'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        self.dlg = LieuxPropicesDialog()

        # show the dialog
        self.dlg.show()
        self.dlg.button_OK.clicked.connect(self.exec)


    def exec(self):

            # récupération des valeurs des paramètres
            gares = self.dlg.coucheGares.currentLayer()
            metros = self.dlg.coucheMetros.currentLayer()
            piscines = self.dlg.couchePiscines.currentLayer()
            espacesVerts = self.dlg.coucheEVs.currentLayer()

            # récupération du fichier de sortie
            outputFile = self.dlg.fichierSortie.filePath()

            if outputFile == "":
                outputFile = 'TEMPORARY_OUTPUT'

            # récupération des valeurs de buffer pour chaque couches

            bufferGares = self.dlg.distanceGares.value()
            bufferMetros = self.dlg.distanceMetros.value()
            bufferPiscines = self.dlg.distancePiscines.value()
            bufferEVs = self.dlg.distanceEVs.value()


            # Calcul des tampons
                     
            tamponGares = processing.run(
                "native:buffer",{
                    'INPUT': gares,
                    'DISTANCE' : bufferGares,
                    'SEGMENTS' :5,
                    'END CAP STYLE' : 0,
                    'JOIN STYLE': 0,
                    'MITER LIMIT' :2,
                    'DISSOLVE' : False,
                    'OUTPUT' : 'TEMPORARY_OUTPUT'
                    })
            
            tamponMetros = processing.run(
                "native:buffer",{
                    'INPUT': metros,
                    'DISTANCE' : bufferMetros,
                    'SEGMENTS' :5,
                    'END CAP STYLE' : 0,
                    'JOIN STYLE': 0,
                    'MITER LIMIT' :2,
                    'DISSOLVE' : False,
                    'OUTPUT' : 'TEMPORARY_OUTPUT'
                    })
            
            tamponPiscines = processing.run(
                "native:buffer",{
                    'INPUT': piscines,
                    'DISTANCE' : bufferPiscines,
                    'SEGMENTS' :5,
                    'END CAP STYLE' : 0,
                    'JOIN STYLE': 0,
                    'MITER LIMIT' :2,
                    'DISSOLVE' : False,
                    'OUTPUT' : 'TEMPORARY_OUTPUT'
                    })
            
            tamponEVs = processing.run(
                "native:buffer",{
                    'INPUT': espacesVerts,
                    'DISTANCE' : bufferEVs,
                    'SEGMENTS' :5,
                    'END CAP STYLE' : 0,
                    'JOIN STYLE': 0,
                    'MITER LIMIT' :2,
                    'DISSOLVE' : False,
                    'OUTPUT' : 'TEMPORARY_OUTPUT'
                    })
            
            # Calculs des 3 intersections (Gares-Métros, Piscines-EVs puis intersection des deux 1ere)

            intersectionGaresMetros = processing.runAndLoadResults(
                "native:intersection", 
                {'INPUT': tamponGares['OUTPUT'],
                'OVERLAY': tamponMetros['OUTPUT'],
                'INPUT_FIELDS':[],
                'OVERLAY_FIELDS':[],
                'OUTPUT': 'TEMPORARY_OUTPUT'})

            intersectionPiscinesEVs = processing.runAndLoadResults(
                "native:intersection", 
                {'INPUT': tamponPiscines['OUTPUT'],
                'OVERLAY': tamponEVs['OUTPUT'],
                'INPUT_FIELDS':[],
                'OVERLAY_FIELDS':[],
                'OUTPUT': 'TEMPORARY_OUTPUT'})

            intersection = processing.runAndLoadResults(
                "native:intersection", 
                {'INPUT': intersectionGaresMetros['OUTPUT'],
                'OVERLAY': intersectionPiscinesEVs['OUTPUT'],
                'INPUT_FIELDS':[],
                'OVERLAY_FIELDS':[],
                'OUTPUT':outputFile})
